### ISSUE TITLE
Gif stuck at some frame

### ISSUE THREAD

**Issue by RahulARanger** [ani-memes/AMII#117]
## About 

Welcoming GIF got stuck at some frame, Applied only to this particular GIF. The remaining Gifs were all working as usual.

![Sengoku Nadeko](https://user-images.githubusercontent.com/57987728/121545574-47616580-ca28-11eb-9350-0c65e247812a.gif)

This is not a big issue, it can be force closed by tapping on it. 

Sorry after looking at the closed issues, found it's #113 

## Info
**PyCharm 2021.1.2 (Community Edition)**
**Windows 10 10.0**
**ani-memes: 0.10.2**

## Logs

These were the error logs that I got
```
java.lang.ArithmeticException: / by zero
	at io.unthrottled.amii.memes.MemePanel.getMemeDuration(MemePanel.kt:461)
	at io.unthrottled.amii.memes.MemePanel.access$getMemeDuration(MemePanel.kt:79)
	at io.unthrottled.amii.memes.MemePanel$runAnimation$animator$1.setFadeOutTimer(MemePanel.kt:435)
	at io.unthrottled.amii.memes.MemePanel$runAnimation$animator$1.paintCycleEnd(MemePanel.kt:425)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Thank you so much for such a great extension. 💖**

**Comment by Unthrottled** [comment]
Look what I did to my poor girl Hanekawa :sob: 

Thank you for taking the time to report this issue. I've seen this error reported and have fixed the issue in the latest release. I was unaware that it was causing this issue though. 

I was going to release the version with the fix earlier this week but ran into some other issues. 

If you want, you can follow the [manual installation instructions](https://github.com/ani-memes/AMII#installation), if you want to test it out. Otherwise, I should have some time this weekend to release the fix.

**Comment by RahulARanger** [comment]
I tried a new extension *0.10.5* and it seems content filters had no effect, so it was hard to see Hanekawa's GIF again. 

while opening IDE,  sometimes gets raised. 
```
Error executing task io.unthrottled.amii.onboarding.UserOnBoarding$attemptToPerformNewUpdateActions$1$1@127e1e2a

java.lang.NoSuchMethodError: 'com.intellij.notification.Notification com.intellij.notification.NotificationGroup.createNotification(java.lang.String, java.lang.String, com.intellij.notification.NotificationType)'
	at io.unthrottled.amii.onboarding.UpdateNotification.display(UpdateNotification.kt:55)
	at io.unthrottled.amii.onboarding.UserOnBoarding$attemptToPerformNewUpdateActions$1$1.run(UserOnBoarding.kt:26)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:403)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:395)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:319)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Unthrottled** [comment]
Cool, thanks, the issue that you posted was the one that prevented me from releasing 0.10.5.

I'll close this issue once I've released 0.10.6 to the jetbrains marketplace.

**Comment by RahulARanger** [comment]
Sure! We will be waiting.

**Comment by Unthrottled** [comment]
@RahulARanger `v0.10.6` is publicly available. Thank you for taking the time to report this issue!
